# Generated by Django 5.0.7 on 2025-11-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('fees', 'Fees'), ('subscription', 'Subscription'), ('other', 'Other')], default='subscription', max_length=40),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='bill_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('fees', 'Fees'), ('subscription', 'Subscription'), ('other', 'Other')], default='subscription', max_length=40),
        ),
    ]
